# Generated by Django 4.2.16 on 2025-01-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0002_alter_student_email_alter_student_missed_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
